const TOGGLE_REPO_SIZE = 'TOGGLE_REPO_SIZE';
const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE';
const TOGGLE_SHOW_TAGS = 'TOGGLE_SHOW_TAGS';
const CHANGE_SORTING_ORDER = 'CHANGE_SORTING_ORDER';

export {
    TOGGLE_REPO_SIZE,
    TOGGLE_DARK_MODE,
    TOGGLE_SHOW_TAGS,
    CHANGE_SORTING_ORDER,
};
